name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'

jobs:
  check-test:
    name: Check and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Test (no-std)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
